// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/user.proto

package user_v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertTelegramUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telegram      *TelegramUser          `protobuf:"bytes,1,opt,name=telegram,proto3" json:"telegram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTelegramUserRequest) Reset() {
	*x = UpsertTelegramUserRequest{}
	mi := &file_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTelegramUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTelegramUserRequest) ProtoMessage() {}

func (x *UpsertTelegramUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTelegramUserRequest.ProtoReflect.Descriptor instead.
func (*UpsertTelegramUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertTelegramUserRequest) GetTelegram() *TelegramUser {
	if x != nil {
		return x.Telegram
	}
	return nil
}

type GetUserByTelegramIDRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TelegramUserId int64                  `protobuf:"varint,1,opt,name=telegram_user_id,json=telegramUserId,proto3" json:"telegram_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserByTelegramIDRequest) Reset() {
	*x = GetUserByTelegramIDRequest{}
	mi := &file_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTelegramIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTelegramIDRequest) ProtoMessage() {}

func (x *GetUserByTelegramIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTelegramIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByTelegramIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByTelegramIDRequest) GetTelegramUserId() int64 {
	if x != nil {
		return x.TelegramUserId
	}
	return 0
}

type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Telegram      *TelegramUser          `protobuf:"bytes,2,opt,name=telegram,proto3" json:"telegram,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetTelegram() *TelegramUser {
	if x != nil {
		return x.Telegram
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TelegramUser struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TelegramUserId int64                  `protobuf:"varint,1,opt,name=telegram_user_id,json=telegramUserId,proto3" json:"telegram_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TelegramUser) Reset() {
	*x = TelegramUser{}
	mi := &file_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramUser) ProtoMessage() {}

func (x *TelegramUser) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramUser.ProtoReflect.Descriptor instead.
func (*TelegramUser) Descriptor() ([]byte, []int) {
	return file_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *TelegramUser) GetTelegramUserId() int64 {
	if x != nil {
		return x.TelegramUserId
	}
	return 0
}

var File_proto_user_proto protoreflect.FileDescriptor

const file_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x10proto/user.proto\x12\x0fjjtsksn.user.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a(easyp_vendor/buf/validate/validate.proto\"^\n" +
	"\x19UpsertTelegramUserRequest\x12A\n" +
	"\btelegram\x18\x01 \x01(\v2\x1d.jjtsksn.user.v1.TelegramUserB\x06\xbaH\x03\xc8\x01\x01R\btelegram\"O\n" +
	"\x1aGetUserByTelegramIDRequest\x121\n" +
	"\x10telegram_user_id\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02(\x01R\x0etelegramUserId\"7\n" +
	"\x12GetUserByIDRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\"\x9a\x01\n" +
	"\x04User\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x04uuid\x129\n" +
	"\btelegram\x18\x02 \x01(\v2\x1d.jjtsksn.user.v1.TelegramUserR\btelegram\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"A\n" +
	"\fTelegramUser\x121\n" +
	"\x10telegram_user_id\x18\x01 \x01(\x03B\a\xbaH\x04\"\x02(\x01R\x0etelegramUserId2\x8c\x02\n" +
	"\vUserService\x12W\n" +
	"\x12UpsertTelegramUser\x12*.jjtsksn.user.v1.UpsertTelegramUserRequest\x1a\x15.jjtsksn.user.v1.User\x12Y\n" +
	"\x13GetUserByTelegramID\x12+.jjtsksn.user.v1.GetUserByTelegramIDRequest\x1a\x15.jjtsksn.user.v1.User\x12I\n" +
	"\vGetUserByID\x12#.jjtsksn.user.v1.GetUserByIDRequest\x1a\x15.jjtsksn.user.v1.UserB0Z.github.com/jjtsksn/us-proto/go/user/v1;user_v1b\x06proto3"

var (
	file_proto_user_proto_rawDescOnce sync.Once
	file_proto_user_proto_rawDescData []byte
)

func file_proto_user_proto_rawDescGZIP() []byte {
	file_proto_user_proto_rawDescOnce.Do(func() {
		file_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)))
	})
	return file_proto_user_proto_rawDescData
}

var file_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_user_proto_goTypes = []any{
	(*UpsertTelegramUserRequest)(nil),  // 0: jjtsksn.user.v1.UpsertTelegramUserRequest
	(*GetUserByTelegramIDRequest)(nil), // 1: jjtsksn.user.v1.GetUserByTelegramIDRequest
	(*GetUserByIDRequest)(nil),         // 2: jjtsksn.user.v1.GetUserByIDRequest
	(*User)(nil),                       // 3: jjtsksn.user.v1.User
	(*TelegramUser)(nil),               // 4: jjtsksn.user.v1.TelegramUser
	(*timestamppb.Timestamp)(nil),      // 5: google.protobuf.Timestamp
}
var file_proto_user_proto_depIdxs = []int32{
	4, // 0: jjtsksn.user.v1.UpsertTelegramUserRequest.telegram:type_name -> jjtsksn.user.v1.TelegramUser
	4, // 1: jjtsksn.user.v1.User.telegram:type_name -> jjtsksn.user.v1.TelegramUser
	5, // 2: jjtsksn.user.v1.User.created_at:type_name -> google.protobuf.Timestamp
	0, // 3: jjtsksn.user.v1.UserService.UpsertTelegramUser:input_type -> jjtsksn.user.v1.UpsertTelegramUserRequest
	1, // 4: jjtsksn.user.v1.UserService.GetUserByTelegramID:input_type -> jjtsksn.user.v1.GetUserByTelegramIDRequest
	2, // 5: jjtsksn.user.v1.UserService.GetUserByID:input_type -> jjtsksn.user.v1.GetUserByIDRequest
	3, // 6: jjtsksn.user.v1.UserService.UpsertTelegramUser:output_type -> jjtsksn.user.v1.User
	3, // 7: jjtsksn.user.v1.UserService.GetUserByTelegramID:output_type -> jjtsksn.user.v1.User
	3, // 8: jjtsksn.user.v1.UserService.GetUserByID:output_type -> jjtsksn.user.v1.User
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_user_proto_init() }
func file_proto_user_proto_init() {
	if File_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_proto_rawDesc), len(file_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_proto_goTypes,
		DependencyIndexes: file_proto_user_proto_depIdxs,
		MessageInfos:      file_proto_user_proto_msgTypes,
	}.Build()
	File_proto_user_proto = out.File
	file_proto_user_proto_goTypes = nil
	file_proto_user_proto_depIdxs = nil
}
